data:
  datapath: 'Data-n-model\NS-Re500_T500_id0.npy'
  Re: 500
  total_num: 100
  offset: 0
  n_sample: 100
  time_interval: 0.5
  nx: 64
  nt: 64
  sub: 1
  sub_t: 1
  shuffle: False

model:
  layers: [32, 32, 32, 32, 32]
  modes1: [4, 4, 4, 4]
  modes2: [4, 4, 4, 4]
  modes3: [4, 4, 4, 4]
  fc_dim: 64

train:
  batchsize: 8
  epochs: 1000
  milestones: [500]
  base_lr: 0.001
  scheduler_gamma: 0.5
  ic_loss: 1.0
  f_loss: 1.0
  xy_loss: 5.0
  save_dir: 'Re500-F'
  save_name: 'PINO-baseline.pt'
  data_iter: 0     # number of update steps on data for each epoch
  eqn_iter: 1       # number of update steps on virtual PDE for each epoch

log:
  project: 'PINO'
  group: 'Re500-05s'
  logfile: 'PINO-baseline-error'


