data:
  name: Burgers
  seed: 1234
  datapath: 'D:\Github\physics_informed\Data-n-model\Dataset\burgers.mat'
  total_num: 1000
  offset: 0
  n_sample: 10
  nx: 128
  nt: 100
  sub: 1
  sub_t: 1
  shuffle: False
  test_ratio: 0.1

model:
  layers: [16, 24, 24, 32, 32]
  modes1: [15, 12, 9, 9]
  modes2: [15, 12, 9, 9]
  fc_dim: 128
  act: gelu
  num_pad: 4


train:
  batchsize: 2
  epochs: 50
  milestones: [200]
  meta_lr: 0.0005
  inner_lr: 0.001
  scheduler_gamma: 0.5
  data_loss: 1.0
  ic_loss: 0.0
  f_loss: 0.0
  inner_ic_loss: 10.0
  inner_f_loss: 1.0
  save_dir: 'Re500-F'
  save_name: 'PINO-iMAML-test.pt'
  data_iter: 0     # number of update steps on data for each epoch
  eqn_iter: 1       # number of update steps on virtual PDE for each epoch

  inner_steps: 100
  reg_params: 10.0

  ckpt: 'Data-n-model\PINO-baseline.pt'

test:
  batchsize: 4

log:
  project: 'PINO-iMAML-meta'
  group: 'Re500-05s-iMAML-meta'
  logfile: 'log\PINO-iMAML-test'


