data:
  seed: 1234
  datapath: 'Data-n-model\NS-Re500_T500_id0.npy'
  Re: 500
  total_num: 100
  offset: 0
  n_sample: 100
  time_interval: 0.5
  nx: 64
  nt: 64
  sub: 1
  sub_t: 1
  shuffle: False
  test_ratio: 0.1

model:
  layers: [32, 32, 32 ,32, 32]
  modes1: [4, 4, 4, 4]
  modes2: [4, 4, 4, 4]
  modes3: [4, 4, 4, 4]
  fc_dim: 64
  
train:
  batchsize: 8
  epochs: 400
  milestones: [200]
  meta_lr: 0.001
  inner_lr: 0.001
  scheduler_gamma: 0.5
  data_loss: 1.0
  inner_ic_loss: 1.0
  inner_f_loss: 1.0
  save_dir: 'Re500-F'
  save_name: 'PINO-MAML-Re500-05s_64_32.pt'
  data_iter: 0     # number of update steps on data for each epoch
  eqn_iter: 1       # number of update steps on virtual PDE for each epoch

  inner_steps: 5
  reg_params: 2.0

  ckpt: 'Data-n-model\PINO-baseline.pt'

test:
  batchsize: 8

log:
  project: 'PINO-maml-meta'
  group: 'Re500-05s-maml-meta'
  logfile: 'log\PINO-maml-meta-error'


