data:
  seed: 1234
  datapath: 'Data-n-model\NS-Re500_T500_id0.npy'
  Re: 500
  total_num: 100
  offset: 0
  n_sample: 100
  time_interval: 0.5
  nx: 64
  nt: 64
  sub: 1
  sub_t: 1
  shuffle: False
  test_ratio: 0.1

model:
  layers: [32, 32, 32, 32, 32]
  modes1: [4, 4, 4, 4]
  modes2: [4, 4, 4, 4]
  modes3: [4, 4, 4, 4]
  fc_dim: 64

train:
  batchsize: 8
  epochs: 100
  milestones: [500]
  inner_lr: 0.001
  scheduler_gamma: 0.5
  ic_loss: 1.0
  f_loss: 1.0
  xy_loss: 0

  ckpt: 'Data-n-model\PINO-iMAML-Re500-05s_64_32.pt'

test:
  batchsize: 8

log:
  project: 'PINO-meta'
  group: 'Re500-05s-meta'
  logfile: 'log\PINO-maml-finetune-100epoch'
