data:
  seed: 1234
  datapath: 'Data-n-model\NS-Re500_T500_id0.npy'
  Re: 500
  total_num: 20
  offset: 0
  n_sample: 20
  time_interval: 0.5
  nx: 64
  nt: 64
  sub: 1
  sub_t: 1
  shuffle: False
  test_ratio: 0.1

model:
  layers: [64, 64, 64, 64, 64]
  modes1: [8, 8, 8, 8]
  modes2: [8, 8, 8, 8]
  modes3: [8, 8, 8, 8]
  fc_dim: 128

train:
  batchsize: 8
  epochs: 10
  milestones: [50]
  meta_lr: 0.01
  inner_lr: 0.01
  scheduler_gamma: 0.5
  ic_loss: 1.0
  f_loss: 1.0
  xy_loss: 5.0
  save_dir: 'Re500-F'
  save_name: 'PINO-meta-Re500-05s_64.pt'
  data_iter: 0     # number of update steps on data for each epoch
  eqn_iter: 1       # number of update steps on virtual PDE for each epoch

  inner_steps: 5
  reg_params: 2.0

test:
  batchsize: 8

log:
  project: 'PINO-meta'
  group: 'Re500-05s-meta'
  logfile: 'log\PINO-meta-error'


