data:
  datapath: 'Data-n-model\NS-Re500_T500_id0.npy'
  Re: 500
  total_num: 500
  offset: 0
  n_sample: 500
  time_interval: 0.5
  nx: 64
  nt: 64
  sub: 1
  sub_t: 1
  shuffle: False

model:
  layers: [64, 64, 64, 64, 64]
  modes1: [8, 8, 8, 8]
  modes2: [8, 8, 8, 8]
  modes3: [8, 8, 8, 8]
  fc_dim: 128

train:
  batchsize: 1
  epochs: 2000
  milestones: [1000]
  base_lr: 0.001
  scheduler_gamma: 0.5
  ic_loss: 10.0
  f_loss: 1.0
  xy_loss: 0
  save_dir: 'Re500-F'
  save_name: 'PINO-fintune-Re500-05s_32.pt'
  data_iter: 0     # number of update steps on data for each epoch
  eqn_iter: 1       # number of update steps on virtual PDE for each epoch
  # ckpt: 'Data-n-model\PINO-pretrain-Re500-05s-4C4.pt'

log:
  project: 'PINO-pretrain-ICLR'
  group: 'Re500-05s-PINO'
  logfile: 'PINO-finetune-error.csv'