data:
  datapath: 'data/NS-Re500_T65_id0 64x65.npy'
  Re: 500
  total_num: 100
  offset: 0
  n_sample: 1
  time_interval: 0.5
  nx: 64
  nt: 65
  sub: 1
  sub_t: 1
  shuffle: True

model:
  layers: [3, 50, 50, 50, 50, 50, 50, 3]
  activation: LAAF-10 tanh

train:
  batchsize: 1
  epochs: 3000
  milestones: [1000, 1500, 2000]
  base_lr: 0.01
  num_domain: 5000
  num_boundary: 10000
  num_test: 100
  log_step: 100

log:
  project: 'PINO-Re500-ICLR'
  group: 'Re500-PINNs'
  logfile: 'log/pinns-plot-laaf128.csv'



