data:
  datapath: 'Data-n-model\Dataset\NS-Re500_T500_id0.npy'  # Path to the dataset file
  Re: 500  # Reynolds number for the NS equation
  total_num: 400  # Total number of data samples
  offset: 0  # Offset to start reading data from
  n_sample: 400  # Number of samples to use from the dataset
  time_interval: 0.5  # Time interval between samples
  nx: 64  # Number of grid points in the spatial dimension (x-direction)
  nt: 64  # Number of time steps
  sub: 1  # Spatial subsampling factor
  sub_t: 1  # Temporal subsampling factor
  shuffle: True  # Whether to shuffle the dataset
  num_ics: 300  # Number of initial conditions for training
  S2: 128  # Spatial resolution for the second stage (e.g., super-resolution)
  T2: 65  # Temporal resolution for the second stage (e.g., super-resolution)
  seed: 1234  # Random seed for reproducibility
  test_ratio: 0.1  # Proportion of data to be used for testing

model:
  layers: [32, 32, 32, 32, 32]  # Number of neurons in each layer of the model
  modes1: [4, 4, 4, 4]  # Number of Fourier modes to use in the x-dimension
  modes2: [4, 4, 4, 4]  # Number of Fourier modes to use in the y-dimension
  modes3: [4, 4, 4, 4]  # Number of Fourier modes to use in the z-dimension
  fc_dim: 64  # Dimension of the fully connected layer
  act: gelu  # Activation function

train:
  batchsize: 8  # Number of samples per batch for training
  epochs: 20000  # Number of epochs for training
  milestones: [10000, 20000, 30000]  # Epoch milestones for learning rate adjustment
  base_lr: 0.001  # Initial learning rate
  scheduler_gamma: 0.5  # Multiplicative factor for learning rate decay at milestones
  ic_loss: 1.0  # Weight for the initial condition loss
  f_loss: 1.0  # Weight for the equation loss
  xy_loss: 5.0  # Weight for the spatial-temporal loss
  save_dir: 'Re500'  # Directory to save the model checkpoints
  save_name: 'PINO-pretrain-400.pt'  # Filename to save the model checkpoint
  data_iter: 4  # Number of iterations for data loss calculation
  eqn_iter: 4  # Number of iterations for equation loss calculation
  ckpt:  # Checkpoint file for resuming training (if any)

log:
  project: 'PINO-pretrain'  # Project name for logging
  group: ''  # Group name for logging
  logfile: 'log\PINO-pretrain-400.log'  # Path to the log file
