data:
  seed: 1234
  datapath: '/home/mou00006/shared/Meta-PINO/data/NS-Re500_T4000_id0.npy'
  Re: 500
  total_num: 400
  offset: 0
  n_sample: 400
  time_interval: 0.5
  nx: 64
  nt: 64
  sub: 1
  sub_t: 1
  shuffle: False
  seed: 1234
  test_ratio: 0.1

model:
  branch_layers: [128, 128, 128, 128, 128, 128]
  trunk_layers: [128, 128, 128, 128, 128, 128]
  activation: 'gelu'
  normalize: 'layernorm'

train:
  batchsize: 4
  epochs: 200
  milestones: [200]
  meta_lr: 0.00001
  inner_lr: 0.0001
  scheduler_gamma: 0.5
  data_loss: 1.0
  ic_loss: 0.0
  f_loss: 0.0
  inner_ic_loss: 10.0
  inner_f_loss: 1.0
  save_dir: 'Re500-deepOnet'
  save_name: 'PIdeepOnet-MAML-400.pt'
  inner_steps: 5
  ckpt: 'Re500-deepOnet\DeepONet-pretrain-400_best.pt'

test:
  batchsize: 2

log:
  logfile: 'log\PIdeepOnet-maml-400'


