data:
  datapath: '/home/mou00006/shared/Meta-PINO/data/NS-Re500_T4000_id0.npy'
  Re: 500
  total_num: 1000
  offset: 0
  n_sample: 1000
  time_interval: 0.5
  nx: 64
  nt: 64
  sub: 1
  sub_t: 1
  shuffle: False

model:
  branch_layers: [128, 128, 128, 128]
  trunk_layers: [128, 128, 128, 128]
  activation: 'gelu'


train:
  batchsize: 8
  epochs: 40000
  milestones: [10000, 20000, 30000]
  ic_loss: 1.0
  f_loss: 1.0
  data_loss: 5.0
  base_lr: 0.001
  scheduler_gamma: 0.5
  save_dir: 'Re500-deepOnet'
  save_name: 'DeepONet-pretrain-1000.pt'
  #ckpt: 'checkpoints/Re500-FDM/pretrain-Re500-05s-4000.pt'

log:
  project: 'PINO-None'
  logfile: 'log/DeepONet-pretrain-1000.log'
  group: 'eval'


